### PR TITLE
Add BZ component to OWNERS

### PR DESCRIPTION
**Pull request by rcarrillocruz**

### CODE REVIEW

**Comment by zshi-redhat** [comment]
do we need a default subcomponent?

**Comment by rcarrillocruz** [comment]
@zshi-redhat i think not, cos there is no subcomponent created for it in BZ, not even sure how to do that

**Comment by zshi-redhat** [comment]
> @zshi-redhat i think not, cos there is no subcomponent created for it in BZ, not even sure how to do that

ack

**Pull request merged**
